version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=custodial_wallet;Username=postgres;Password=postgres;
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    container_name: custodial_wallet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: custodial_wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: